# Feature Engineering
### **Mohon membaca setiap instruksi dan tag komentar dengan saksama sebelum melanjutkan pengerjaan.**

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from sklearn.model_selection import train_test_split

# Scalling untuk MinMax Scaller
from sklearn.preprocessing import MinMaxScaler
# Set the maximum number of columns and rows to display to a large number
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

# B. Outlier Handling

### Outlier Handling : InterQuartile Handling

In [ ]:
# untuk plot Q-Q
import scipy.stats as stats

In [ ]:
df_california = pd.read_csv('california_dataset.csv')

In [ ]:
from sklearn.model_selection import train_test_split
# splitting terlebih dahulu
train_clfr, test_clfr = train_test_split(df_california, test_size = 0.2, random_state=42)

#NOTES :
#train : test = 80:20 atau 75:25 atau (minimum :70:30 atau maksimum: 90:10) bagi angka yg lain (85:15)
#data train di-handling outliernya
#tapi tidak untuk data test, karena data test ibarat representasi data masa depan yang digunakan untuk melihat performa Machine Learning

### Assignment 1.a :
1. lakukan looping untuk melihat plot distribusi data dan outlier pada kolom-kolom : ['MedInc', 'HouseAge', 'AveRooms','AveBedrms', 'AveOccup'] di california_dataset.csv
2. Daftar nama kolom yang Anda cek, kolom_kolom = ['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'AveOccup']

In [ ]:
# Assignment 1.a : lakukan looping untuk melihat plot distribusi data dan outlier pada kolom-kolom : ['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'AveOccup'] di california_dataset.csv
# Daftar nama kolom yang ingin Anda cek
df_california.columns

### Assignment 1.b
1. Lakukan handling outlier pilih 1 kolom saja yang di handling dengan IQR setelah mengecek distribusinya
2. Dan cek distribusinya kembali

In [ ]:
df = pd.read_csv('company.csv')
df.head()

In [ ]:
### Assignment 1.b Lakukan handling outlier pilih 1 kolom saja yang di handling dengan IQR setelah mengecek distribusinya
### Dan cek distribusinya kembali
sns.histplot(df['Revenue'], kde=True)
plt.title('Distribution Before Outlier Handling')
plt.show()

sns.boxplot(x=df['Revenue'])
plt.title('Boxplot Before Outlier Handling')
plt.show()

In [ ]:
df['Revenue'] = pd.to_numeric(df['Revenue'], errors='coerce')

In [ ]:
Q1 = df['Revenue'].quantile(0.25)
Q3 = df['Revenue'].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

print("Lower:", lower_bound)
print("Upper:", upper_bound)

In [ ]:
df_clean = df[(df['Revenue'] >= lower_bound) & (df['Revenue'] <= upper_bound)]

In [ ]:
sns.histplot(df_clean['Revenue'], kde=True)
plt.title('Distribution After Outlier Handling')
plt.show()

sns.boxplot(x=df_clean['Revenue'])
plt.title('Boxplot After Outlier Handling')
plt.show()

# C. Missing Value Handling
Missing Value Merupakan nilai yang hilang di suatu kolom, namun tidak hanya sebatas itu. Untuk nilai yang tidak sesuai tapi muncul didalam suatu kolom tertentu juga bisa dianggap sebagai missing value. Misal tipenya kategorikal tapi isinya ada yang berupa angka dan juga sebaliknya.

In [ ]:
df_company = pd.read_csv('company.csv')

### Aturan missing value handling :
1. jika tipe datanya itu **numerik** -> handling menggunakan **median** (robust / tahan terhadap outlier)
2. jika tipe datanya itu **kategorik / object / string** -> handling menggunakan **mode / modus**

In [ ]:
!pip install feature_engine

In [ ]:
df = pd.read_excel('titanic.xlsx')

In [ ]:
from sklearn.model_selection import train_test_split
#Splitting terlebih dahulu
train_titanic, test_titanic = train_test_split(df, test_size = 0.2, random_state=42)
#train : test = 80:20 atau 75:25 atau (minimum :70:30 atau maksimum: 90:10) bagi angka yg lain (85:15)

## Assignment 2. Missing Value Handling :
1. Cek persentase missing value pada kolom Headquarters di company.csv, Cek jenis missing valuenya ?
2. apakah di drop atau tidak (gunakan syarat drop kolom jika > 20%)
3. jika tidak maka handling, dan dengan cara apa handling nilainya, median atau modus ?

In [ ]:
#Tulis jawaban missing value handling kolom Headquarters disini
missing = df_company['Headquarters'].isnull().sum()
missing_percent = (missing / len(df)) * 100

print('Missing Value:', missing)
print('Percentage:', missing_percent, '%')

In [ ]:
if missing_percent > 20:
    df = df.drop(columns=['Headquarters'])
    print('Column dropped because missing value > 20%')
else:
    print('Column not dropped, proceed to handling')

In [ ]:
mode_value = df_company['Headquarters'].mode()[0]
df_company['Headquarters'].fillna(mode_value, inplace=True)

print('Missing values filled with mode:', mode_value)

In [ ]:
df_company['Headquarters'].isnull().sum()

# D. Encoding
Definisi : Mengubah tipe kategorikal menjadi numerikal dengan pendekatan aturan encoding untuk persiapan sebelum dilakukannya machine learning modelling. Teknik Encoding yang umum dipakai :
1. One Hot Encoding (OHE) : Lakukan pada kolom gender
2. Label Encoding / Ordinal Encoding : Lakukan pada kolom Yes dan No, Jika Yes menjadi 1 , Jika No menjadi 0. Sebagai Contohnya di kolom  Partner, Dependents.
3. Mean Encoding : Contract

In [ ]:
df_churn = pd.read_csv('/home/robot/Documents/sem6/machine_learning/Week2/TelcoCustomerChurn.csv')
df.head()

In [ ]:
df.info()

In [ ]:
df.describe()

In [ ]:
from sklearn.model_selection import train_test_split
#Splitting terlebih dahulu
train_clfr, test_clfr = train_test_split(df_churn, test_size = 0.2, random_state=42)

## Assignment 3.a Label Encoder :
1. Pilih kolom-kolom StreamingMovies, StreamingTV, TechSupport, DeviceProtection, OnlineBackup, OnlineSecurity, MultipleLines
2. Ganti nilai yang tidak sesuai : No internet service menjadi No lalu validasi dengan value_counts
3. Kemudian lakukan label Encoder
4. Notes : gunakan Telco-Customer-Churn.csv

In [1]:
#Tulis jawaban
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [4]:
df = pd.read_csv('TelcoCustomerChurn.csv')
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [5]:
cols = [
    'StreamingMovies',
    'StreamingTV',
    'TechSupport',
    'DeviceProtection',
    'OnlineBackup',
    'OnlineSecurity',
    'MultipleLines'
]

df_selected = df[cols]
df_selected.head()

,StreamingMovies,StreamingTV,TechSupport,DeviceProtection,OnlineBackup,OnlineSecurity,MultipleLines
0,No,No,No,No,Yes,No,No phone service
1,No,No,No,Yes,No,Yes,No
2,No,No,No,No,Yes,Yes,No
3,No,No,Yes,Yes,No,Yes,No phone service
4,No,No,No,No,No,No,No

In [6]:
for col in cols:
    print(f"\n{col}")
    print(df_selected[col].value_counts())

StreamingMovies
StreamingMovies
No                     2785
Yes                    2732
No internet service    1526
Name: count, dtype: int64

StreamingTV
StreamingTV
No                     2810
Yes                    2707
No internet service    1526
Name: count, dtype: int64

TechSupport
TechSupport
No                     3473
Yes                    2044
No internet service    1526
Name: count, dtype: int64

DeviceProtection
DeviceProtection
No                     3095
Yes                    2422
No internet service    1526
Name: count, dtype: int64

OnlineBackup
OnlineBackup
No                     3088
Yes                    2429
No internet service    1526
Name: count, dtype: int64

OnlineSecurity
OnlineSecurity
No                     3498
Yes                    2019
No internet service    1526
Name: count, dtype: int64

MultipleLines
MultipleLines
No                  3390
Yes                 2971
No phone service     682
Name: count, dtype: int64

In [7]:
df_selected = df_selected.replace('No internet service', 'No')

In [8]:
for col in cols:
    print(f"\n{col}")
    print(df_selected[col].value_counts())

StreamingMovies
StreamingMovies
No     4311
Yes    2732
Name: count, dtype: int64

StreamingTV
StreamingTV
No     4336
Yes    2707
Name: count, dtype: int64

TechSupport
TechSupport
No     4999
Yes    2044
Name: count, dtype: int64

DeviceProtection
DeviceProtection
No     4621
Yes    2422
Name: count, dtype: int64

OnlineBackup
OnlineBackup
No     4614
Yes    2429
Name: count, dtype: int64

OnlineSecurity
OnlineSecurity
No     5024
Yes    2019
Name: count, dtype: int64

MultipleLines
MultipleLines
No                  3390
Yes                 2971
No phone service     682
Name: count, dtype: int64

In [9]:
le = LabelEncoder()

for col in cols:
    df_selected[col] = le.fit_transform(df_selected[col])

In [10]:
for col in cols:
    print(f"\n{col} mapping:")
    print(dict(zip(le.classes_, le.transform(le.classes_))))

StreamingMovies mapping:
{'No': np.int64(0), 'No phone service': np.int64(1), 'Yes': np.int64(2)}

StreamingTV mapping:
{'No': np.int64(0), 'No phone service': np.int64(1), 'Yes': np.int64(2)}

TechSupport mapping:
{'No': np.int64(0), 'No phone service': np.int64(1), 'Yes': np.int64(2)}

DeviceProtection mapping:
{'No': np.int64(0), 'No phone service': np.int64(1), 'Yes': np.int64(2)}

OnlineBackup mapping:
{'No': np.int64(0), 'No phone service': np.int64(1), 'Yes': np.int64(2)}

OnlineSecurity mapping:
{'No': np.int64(0), 'No phone service': np.int64(1), 'Yes': np.int64(2)}

MultipleLines mapping:
{'No': np.int64(0), 'No phone service': np.int64(1), 'Yes': np.int64(2)}

## Selesai :)